//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppVilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int PropertyID { get; set; }
        public string Category { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Rooms { get; set; }
        public string Parking { get; set; }
        public string PaymentProcess { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
